// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2Po_y8s2i4u0Ap3pjq2U7BmqN-v5Inqg',
    appId: '1:126683731134:web:66cbe3c63004c40d0c3aef',
    messagingSenderId: '126683731134',
    projectId: 'spotify-aef98',
    authDomain: 'spotify-aef98.firebaseapp.com',
    storageBucket: 'spotify-aef98.firebasestorage.app',
    measurementId: 'G-CNCEE8MDEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB11kem1KlESVbtSf3DZcddYDBFDVPgK0I',
    appId: '1:126683731134:android:bac7edc95855396e0c3aef',
    messagingSenderId: '126683731134',
    projectId: 'spotify-aef98',
    storageBucket: 'spotify-aef98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFPFlNKLoAFR4RxCwWPTDELPQYzYZfeOM',
    appId: '1:126683731134:ios:7622a5468f570ef70c3aef',
    messagingSenderId: '126683731134',
    projectId: 'spotify-aef98',
    storageBucket: 'spotify-aef98.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFPFlNKLoAFR4RxCwWPTDELPQYzYZfeOM',
    appId: '1:126683731134:ios:7622a5468f570ef70c3aef',
    messagingSenderId: '126683731134',
    projectId: 'spotify-aef98',
    storageBucket: 'spotify-aef98.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2Po_y8s2i4u0Ap3pjq2U7BmqN-v5Inqg',
    appId: '1:126683731134:web:62998c485277b96e0c3aef',
    messagingSenderId: '126683731134',
    projectId: 'spotify-aef98',
    authDomain: 'spotify-aef98.firebaseapp.com',
    storageBucket: 'spotify-aef98.firebasestorage.app',
    measurementId: 'G-K1Z7C4T4T3',
  );
}
